export enum ORDER_STATUS_ENUM {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
}
export enum PAYMENT_STATUS_ENUM {
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED ',
}
